### ISSUE TITLE
About the backbone

### ISSUE THREAD

**Issue by hellozhuo** [AndreKelm/RefineContourNet#1]
Dear author, 

I am wondering is the backbone in RCN (the residual blocks) pretrained on large-scale dataset like ImageNet?
Or the whole network is randomly initialized and trained on the CRF-refined object contour dataset/modified COCO dataset?

**Comment by AndreKelm** [comment]
The ResNet backbone is already pre-trained on ImageNet and then fine-trained for the detection task. Sorry for the late reply! I hope it helps anyway.
