### ISSUE TITLE
about NMS

### ISSUE THREAD

**Issue by CoachingJane** [AndreKelm/RefineContourNet#2]
I use the NMS code from https://github.com/xwjabc/hed,like
![image](https://user-images.githubusercontent.com/44397199/110606470-2ee17500-81c5-11eb-8f0d-f7e49953c645.png)
I run this code with your RCN_results_on_PASCAL_val, get the totally different result like
![image](https://user-images.githubusercontent.com/44397199/110606835-90094880-81c5-11eb-9461-7c8a5fa68831.png)
![image](https://user-images.githubusercontent.com/44397199/110606960-add6ad80-81c5-11eb-80b4-f494acd2d455.png)
and your nmsed img are
![image](https://user-images.githubusercontent.com/44397199/110607091-d2cb2080-81c5-11eb-93a2-32af682cc097.png)
![image](https://user-images.githubusercontent.com/44397199/110607120-d9599800-81c5-11eb-8c36-6342b423cd75.png)
could you tell me where is your NMS code?or do you know what makes they different,thank you

**Comment by AndreKelm** [comment]
Hi Jane,
looking at the examples - it looks like the problem is a different image format. For our work, we changed to a more accurate format (16 bits for each pixel, instead of the previous 8 bits). We mentioned this in the paper because it is beneficial for the results. Additionally, we used the .tiff format to avoid confusion with the 8-bit .png from the start.
Example of pixel values:
![16bit_image](https://user-images.githubusercontent.com/60356944/110632992-87eee000-81a8-11eb-9529-592389a312c4.PNG)
You can change the code from the NMS (we modified Piotr Dollar's toolbox) so that you can use 16-bit images or change our results from 16 to 8 bits.

Please let me know if this was helpful,
André

**Comment by CoachingJane** [comment]
nice
i deal it with 
![image](https://user-images.githubusercontent.com/44397199/110931347-1ad47980-8365-11eb-9a42-d8e73f2ab861.png)
then 
![image](https://user-images.githubusercontent.com/44397199/110931829-ac43eb80-8365-11eb-9c1a-6896d2cb9029.png)
![image](https://user-images.githubusercontent.com/44397199/110931845-b239cc80-8365-11eb-8cc9-de421404878a.png)
just a little different from yours

**Comment by CoachingJane** [comment]
by the way could you tell me your ods ois ap R50?i what to compare the score of your eval_code and mine,thank you!

**Comment by AndreKelm** [comment]
For results, check the preprint: https://arxiv.org/pdf/1904.13353.pdf or the publication https://link.springer.com/chapter/10.1007%2F978-3-030-29888-3_20
For evaluation, we use a subset of 1103 images of a CRF-refined PASCAL val2012. So, when you are not using CRF-refined labels, the values of the Optimal Dataset Scale, Optimal Image Scale and the Average Precision should be lower and we cannot compare the score of the evaluation code. Are you using CRF-refined labels or the originals? Are you having the same subset?

**Comment by CoachingJane** [comment]
YES!,I use the VOC2007+2012 trainset(CRF-refined labels,10582 images) for training , VOC2007+2012 valsetCRF-refined labels(1443 images)for eval from this paper Object Contour Detection with a Fully Convolutional Encoder-Decoder Network(https://arxiv.org/pdf/1603.04530.pdf),,:
trainset:
![image](https://user-images.githubusercontent.com/44397199/111016913-6467a780-83eb-11eb-9a9d-f3b1135d333d.png)
(2007_000032)
![image](https://user-images.githubusercontent.com/44397199/111016938-7fd2b280-83eb-11eb-8a6c-8070148d88d7.png)
(2008_000266)
valset:
![image](https://user-images.githubusercontent.com/44397199/111016210-7e06f000-83e7-11eb-84a2-de1cc1caf8a9.png)
(2008_000009)
![image](https://user-images.githubusercontent.com/44397199/111016279-e786fe80-83e7-11eb-9f76-0ec29f5d69ac.png)
(2008_000863）

In this paper（Object Contour Detection with a Fully Convolutional Encoder-Decoder Network）, the author use the originally annotated contours for eval, and CRF-refined labels for train:
![image](https://user-images.githubusercontent.com/44397199/111016349-48163b80-83e8-11eb-8b3b-391d25e77e00.png)
But when i create the "originally annotated contours ", I gei the white area like:
![image](https://user-images.githubusercontent.com/44397199/111016382-8b70aa00-83e8-11eb-8061-de70645c8387.png)
(2008_000863)(Do you know how to deal these white area? I create it just from the SegmentationObject set...)

whether the labels  that i used is right? or If it's convenient for you, Could  you provide the data set you use in your code？thank you！

**Comment by CoachingJane** [comment]
I ues your dataset(1103 images) to eval, the GT is CRF-refined labels with uint8 format:
![image](https://user-images.githubusercontent.com/44397199/111031536-fcdd4680-8442-11eb-96b3-55c27cbba358.png)
and change your nms image to uint8 too:
![image](https://user-images.githubusercontent.com/44397199/111031562-2302e680-8443-11eb-9f47-01d2efd852bd.png)
then get the result:
![image](https://user-images.githubusercontent.com/44397199/111031581-3c0b9780-8443-11eb-8b79-25bb620b6010.png)
![image](https://user-images.githubusercontent.com/44397199/111031590-4168e200-8443-11eb-8e44-febfefbac0f2.png)
it seems the scores are too low? i dont know whether the image format will affect the scores so much？
the original paper' result is:
![image](https://user-images.githubusercontent.com/44397199/111031697-c3f1a180-8443-11eb-832a-0f25832edfdf.png)
(i think there must something wrong, have you try ro eval the dataset with uint8?)

**Comment by AndreKelm** [comment]
- this precision and recall curve does not look correct - recall very low -> many false negatives
- the image format (8 or 16 bit) does not make such a big difference
- the labels are in uint8 format? you can check if the labels contain only the needed binary information
- the white areas? yes, the white area sometimes gives more information than just the contours, I think the intention was to label the unlabeled area (like object contours) - but too many of these white areas explains the bad precision-recall curve
![grafik](https://user-images.githubusercontent.com/60356944/111042447-bfc28580-843d-11eb-907c-d6f54b3b373a.png)
- maybe check the segmentation class instead of the segmentation object

Please let me know if this leads further

**Comment by CoachingJane** [comment]
the original code that I used to eval is for eval the BSDS , since the BSDS have 6 edge-GT:
![image](https://user-images.githubusercontent.com/44397199/111100938-d4109a80-8583-11eb-90a7-d83af54b38b6.png)
and storaged as logical:
![image](https://user-images.githubusercontent.com/44397199/111100967-e12d8980-8583-11eb-99e3-a6e75413a656.png)
and we have only one edge-GT, and the format is uint8, so I just refined one line:
![image](https://user-images.githubusercontent.com/44397199/111101243-76308280-8584-11eb-8090-e2f18c08e342.png)
So I think the code is right
As for the format of images,  GT and eval-image are all uint8:
![image](https://user-images.githubusercontent.com/44397199/111101394-c14a9580-8584-11eb-8583-d2a78a0ca320.png)
![image](https://user-images.githubusercontent.com/44397199/111101463-edfead00-8584-11eb-890e-35653c0d1769.png)
By the way , I try to nms the GT:
![image](https://user-images.githubusercontent.com/44397199/111101579-2d2cfe00-8585-11eb-99ce-8d8d7f2e181f.png)
![image](https://user-images.githubusercontent.com/44397199/111101633-4a61cc80-8585-11eb-98e1-9013b941b456.png)
![image](https://user-images.githubusercontent.com/44397199/111101736-78dfa780-8585-11eb-80fd-248cd7d07a10.png)
![image](https://user-images.githubusercontent.com/44397199/111101764-82690f80-8585-11eb-8928-237bbbfa0de6.png)
and ues nme-GT to eval, then get the result:
![image](https://user-images.githubusercontent.com/44397199/111101789-93198580-8585-11eb-9f6b-4630a591dd24.png)
![image](https://user-images.githubusercontent.com/44397199/111101801-9b71c080-8585-11eb-8a9b-6841d87a9c69.png)
But there is still a big gap between this and the scores in the paper
Maybe I will use your code next，before this, if it's convinent for you , could you offer your edge-GT set?  it will help me a lot.
and thank you again for your serious reply！

**Comment by AndreKelm** [comment]
Youre Welcome! The score looks more and more realistic. I have added the subset of 1103 refined GT and images to the repository.
Example:
![grafik](https://user-images.githubusercontent.com/60356944/111140894-27361d80-8583-11eb-838b-7f5f42b9b399.png)

**Comment by CoachingJane** [comment]
wow！ The scores reached the level close to the paper！
![image](https://user-images.githubusercontent.com/44397199/111246011-89088d00-8640-11eb-9696-89dba7ecf4e0.png)
![image](https://user-images.githubusercontent.com/44397199/111246181-c705b100-8640-11eb-81cb-a21eb5223bea.png)
So the eval-code is not the problem，my NMS code ande GT have something wrong! 

Let me look back, There's something strange about my NMS code（ from https://github.com/xwjabc/hed ）
![image](https://user-images.githubusercontent.com/44397199/111246846-f8cb4780-8641-11eb-9cd9-06c9f682a482.png)
this code' author, add the function convTri(), a 2D image convolution with a triangle filter, I dont know why the author add this code ,buy it does make the result different(Strangely, other conclusions such as hed, rcf have not been affected, that confuse me a lot)
Another mistake is my GT, at the beginning, I thought the CRF-refined imgs are the GT
![image](https://user-images.githubusercontent.com/44397199/111249663-059e6a00-8647-11eb-8857-2089727b98cc.png)
but actually, the edges after thinning can be used as GT(right?)
![image](https://user-images.githubusercontent.com/44397199/111249788-37afcc00-8647-11eb-8dfb-9d4ee60fdcbb.png)

I look for other versions of the NMS-code on the Internet,it's almost the same except for that line of code.
But when I use MY NMS-code and try to thin the CRF-refined GT, I found it  did not work:
CRF-refined-img:
![image](https://user-images.githubusercontent.com/44397199/111250876-15b74900-8649-11eb-9ef4-665f22bc4841.png)
NMS-CRF-refined-img:
![image](https://user-images.githubusercontent.com/44397199/111250817-ef91a900-8648-11eb-845b-4f7ea25e305f.png)
your img:
![image](https://user-images.githubusercontent.com/44397199/111250913-2a93dc80-8649-11eb-9344-824caba42591.png)
and when I used my NMS code before，I don't know if you remember，my edge is a little different from yours：
![image](https://user-images.githubusercontent.com/44397199/111252122-6c258700-864b-11eb-8375-948d333b3f22.png)
![image](https://user-images.githubusercontent.com/44397199/111252207-8ceddc80-864b-11eb-9f04-be8f2fc5224c.png)
![image](https://user-images.githubusercontent.com/44397199/111252215-95461780-864b-11eb-8ba9-a0e262e02add.png)

that confused me.....I'm mean, I dont understand how you get these edge? is that NMS？If that's the way you do it, could you tell me where is your NMS code? course I didnt find the NMS code in this repository.  thank you!

**Comment by AndreKelm** [comment]
The PR curve looks good. Small changes to the GT can greatly affect the results because of possible mismatches.

The CRF refined labels ARE the GT. Using an NMS on them causes new problems because then no maximum pixel can be found (maybe it chooses the middle pixel). I think you have to create them according to the paper from: https://openaccess.thecvf.com/content_cvpr_2016/papers/Yang_Object_Contour_Detection_CVPR_2016_paper.pdf.
They should be similar to my example.

We used the NMS code from Piotr Dollar and his toolbox: https://github.com/pdollar/toolbox

I remember challenging times to figure out all this evaluation stuff :)

And I hope this was helpful again!

**Comment by CoachingJane** [comment]
So GT is not obtained by NMS method, but by other methods 
I will try to use the code you mentioned and if there is anyth new I will  uploa it
I tried to contact the author of other versions of code, but no one answered me
thank you，you are really a warm-hearted person！

**Comment by AndreKelm** [comment]
Thanks for the flowers - I will leave this topic open for some time in case something new comes up

**Comment by CoachingJane** [comment]
there are something interesting(or maybe it's unimportant，then you could just ignore this comment)，I use my nms code(your CRF_refined imgs) and your GT，then get the result:
![image](https://user-images.githubusercontent.com/44397199/111404873-7e1a2f00-870a-11eb-9d11-740db94f14bc.png)
your paper's result is:
![image](https://user-images.githubusercontent.com/44397199/111404942-99853a00-870a-11eb-9883-b6dcb6a1e045.png)

nmsed imgs:
![image](https://user-images.githubusercontent.com/44397199/111405194-0698cf80-870b-11eb-905a-a18a46cf71aa.png)
![image](https://user-images.githubusercontent.com/44397199/111405206-0bf61a00-870b-11eb-8106-1666b448a44d.png)

**Comment by AndreKelm** [comment]
Hi,
Nice! Yes, that makes perfect sense to me. My experience is that the evaluation of the f-score (ODS) is better when the contour is not perfectly thinned (probably because you miss less of the positive contour pixels). Since we wanted to attack the state of the art - I made sure that the f-score is very valid - I read that the evaluation should be slightly more correct if the contour is thinned to 1-pixel wide contours. This is one reason why we switched to the 16-bit representation. With this representation it was possible for the NMS to detect the maximum and generate 1-pixel wide object contours.

One thing I don't understand - you wrote that you are evaluating the CRF refined against the GT? That doesn't make sense - I assume you are using the RCN-NMS results against the GT (CRF refined).

**Comment by CoachingJane** [comment]
I use my nms code to the img(that your offered in this repository: RCN_results_on_PASCAL_val), and my nmsed imgs have some different from your nmsed imgs , my imgs have a little bit thicker than yours，and GT used is the same from this repository that you offered a few days ago :PASCAL val2012 subset refined GT.
my nms code:
![image](https://user-images.githubusercontent.com/44397199/111590720-72f5fa80-8801-11eb-9cca-e8dbf1d5589c.png)
(actually use E=single(im2uint8(x))/255; but not E=convTri(single(im2uint8(x))/255,1); you will get the same result, but this code can not thin the CRF-GT, when you use E=single(im2uint8(x))/255; to the CRF-GT, Nothing will happen, I dont know why....)

CRF-GT:
![image](https://user-images.githubusercontent.com/44397199/111590533-2ca09b80-8801-11eb-83f7-759f0c562d72.png)

your predict img(RCN_results_on_PASCAL_val):
![image](https://user-images.githubusercontent.com/44397199/111590682-64a7de80-8801-11eb-9236-2d98b236dcbd.png)

mnsed_predict_img:
![image](https://user-images.githubusercontent.com/44397199/111590608-48a43d00-8801-11eb-9bbd-dcf38aa1c555.png)

your nmsed_predict_img:
![image](https://user-images.githubusercontent.com/44397199/111592786-35df3780-8804-11eb-8af9-ed984fe1aaeb.png)

nmsed_CRF_GT:
![image](https://user-images.githubusercontent.com/44397199/111591478-7938a680-8802-11eb-9dd6-3c092d37eebe.png)
(at the beginning i thought your GT(PASCAL val2012 subset refined GT)is just use nms to the CRF-GT,but they look a little different)

The operation of the first paragraph is that I get the code and data set used in the  scores：
![image](https://user-images.githubusercontent.com/44397199/111593662-23b1c900-8805-11eb-8bf0-31adb6f7956a.png)

I hope this was helpful.

**Comment by CoachingJane** [comment]
If it is convenient, could you offer your hed model or code? because no matter how I train hed model, I can't get the accuracy of 58.7(ODS) in the paper,thank you!

**Comment by AndreKelm** [comment]
For the comparison in the paper we did not train any other methods - fortunately most researchers provided their already trained models or their image results.

The necessary material for the HED data - I get here from Anna Khoreva: https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/weakly-supervised-learning/weakly-supervised-object-boundaries/

**Comment by CoachingJane** [comment]
thank you! Are you using the pictures in this folder？
![image](https://user-images.githubusercontent.com/44397199/114666833-516d2d80-9d31-11eb-8fa9-a9ec00aa2ad8.png)
and have these pictures been processed by NMS？（cause they look strange）
![image](https://user-images.githubusercontent.com/44397199/114667185-c17bb380-9d31-11eb-8db2-e200f1e3a0c7.png)

**Comment by AndreKelm** [comment]
HED_VOC should be correct. Please ask @ankhoreva for more details. From the naming no NMS should have been applied and I think thats how I used them but you are right they look a bit like this.

If you want to evaluate further on BSDS500 - please tell me - Then I would like to get rid of one more tip that helped me a lot.

**Comment by CoachingJane** [comment]
BSDS? which method? if you mean the method in paper Weakly Supervised Object Boundaries, the author offered the result:
![image](https://user-images.githubusercontent.com/44397199/114810043-e168b100-9ddd-11eb-9db5-a920196d43ec.png)
Actually, I don't know the content of this paper very well，its a little complex(for example ,I dont know what the HED_cons._all_methods mean😂)

if you mean other method just tell me, I will try it.
anyway I will try to evaluet images in HED_VOC, and i will upload the result

In another paper Convolutional Oriented Boundaries:
![image](https://user-images.githubusercontent.com/44397199/114811168-33aad180-9de0-11eb-988d-315911c2a27d.png)
the author get the scores:
![image](https://user-images.githubusercontent.com/44397199/114811210-445b4780-9de0-11eb-8fc6-db43aa3e62b3.png)
In Weakly Supervised Object Boundaries, the author use original voc2012 set to train and eval:
![image](https://user-images.githubusercontent.com/44397199/114812110-f21b2600-9de1-11eb-9bef-4e5325efd526.png)
and get the result:
![image](https://user-images.githubusercontent.com/44397199/114812241-2a226900-9de2-11eb-8df2-c7acb732960b.png)
This is understandable. After all, there are more training data, but its confused because they seems to get different scores from your paper?

**Comment by CoachingJane** [comment]
the images in HED_VOC get the scores just as your paper:
![image](https://user-images.githubusercontent.com/44397199/114862303-ef8bf100-9e20-11eb-8f38-487f6f52de02.png)
But it's so strange! The images I predicted looked much better than his, but they didn't get that high score！

my predicted image:
![image](https://user-images.githubusercontent.com/44397199/114862611-514c5b00-9e21-11eb-8864-e22e475ff7ac.png)
![image](https://user-images.githubusercontent.com/44397199/114862629-55787880-9e21-11eb-93bd-65e7c727b6c9.png)
![image](https://user-images.githubusercontent.com/44397199/114862653-5dd0b380-9e21-11eb-8139-7fd618aa7029.png)
![image](https://user-images.githubusercontent.com/44397199/114862674-645f2b00-9e21-11eb-8058-f7e25393a8e3.png)

predicted images offered by Weakly Supervised Object Boundaries:
![image](https://user-images.githubusercontent.com/44397199/114862794-89539e00-9e21-11eb-91ae-90948be4875e.png)
![image](https://user-images.githubusercontent.com/44397199/114862843-98d2e700-9e21-11eb-9056-f985f5835bf3.png)
![image](https://user-images.githubusercontent.com/44397199/114862855-9c666e00-9e21-11eb-90da-e4ccaed9a3ab.png)
![image](https://user-images.githubusercontent.com/44397199/114862864-9ff9f500-9e21-11eb-83a3-8bfe967932cd.png)

As you can see clearly, the non object edges on the image I predicted are much less than what he got！

**Comment by AndreKelm** [comment]
The evaluation gives the ODS or f-score, so you can compare where your algorithm works well and where it doesn't - I mean, whether it is better in recall or precision than the other methods. Then you know what you need to improve the algorithm.

The BSDS500 is or was the standard benchmark for edge detection, but I think there are some new benchmarks - always good to check the paperswithcode website...

The tip - I had in mind is that the work from RicherConvolutionalFeatures  (yun-liu /
plot-edge-pr-curves) provided a lot of methods and their PR-curve for the BSDS500 benchmark. This was awesome :-)

I think the original topic is solved. You can search my name and institution to find my email, if there are more questions.
