### ISSUE TITLE
LFS fail

### ISSUE THREAD

**Issue by Howardyangyixuan** [AndreKelm/RefineContourNet#3]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/AndreKelm/RefineContourNet.git/info/lfs'

It seems there is something wrong with your LFS repo. Could you please upload your pre-trained model link in another way? Great thanks

**Comment by AndreKelm** [comment]
The LFS system seems to have a bandwidth limitation at GitHub. However, the problem has been fixed and everything should now work as intended again.
