### ISSUE TITLE
How can I see the details of the net  structure？

### ISSUE THREAD

**Issue by jjkkqq** [AndreKelm/RefineContourNet#5]
hi！ I load the net like :
![image](https://user-images.githubusercontent.com/84672820/119265085-0986d380-bc18-11eb-9d67-2e294926bb3f.png)
but it seems that specific information about the network cannot be obtained:
![image](https://user-images.githubusercontent.com/84672820/119265139-3a670880-bc18-11eb-8e0c-ed4a53390e78.png)
（when I use dagnn.DagNN.loadobj to load ,there will be some wrongs）
So, could you tell me where can get the details of your net?
thank you.

**Comment by AndreKelm** [comment]
Hi, we have described the used structure of the network in the paper. I remember a MatconvNet script that can visualize more details. I will check it and let you know

**Comment by jjkkqq** [comment]
thank you for your reply
Your paper describes the structure of the network, and I want to know more about the parameters in the network, such as convolution core size, stride size and so on
thank you

**Comment by AndreKelm** [comment]
You can visualize MatConvNet architectures using visualize_matconvnet from @layumi.
We used ResNet101 as a backbone, so a Residual Unit contains three conv layers with a bottleneck design. In total, we used about 81.4 million parameters with 148 conv layers. The core size is mainly 3, and the stride is 1. If the input and output have different dimensions, then the bottleneck connection path has a 1 x 1 conv layer. The whole network is strongly based on RefineNet and differs only in the loss function. Hope this helps.

**Comment by CoachingJane** [comment]
I encountered some problems during compilation. Could you tell me what the network detection speed (FPS) is? Thank you!
