### ISSUE TITLE
How do you get CEDN's scores(0.654) on your val set(1103)?

### ISSUE THREAD

**Issue by stupidman98** [AndreKelm/RefineContourNet#8]
I implement CEDN by Pytorch and re-train it on CRF-refined Pascal VOC, but it scores 0.752, which is much different with your record in paper

**Comment by AndreKelm** [comment]
In the original CEDN publication, they have an F-score of 0.57 for PASCAL val2012. In the refined subset PASCAL val2012 of my paper, it is better at 0.65. But I really don't know how to get this high value.

Some reasons:
- Did you really implement the same architecture or did you use residual connections or a different backbone?
- Did you train with some val images?

I hope this is helpful
